# Generated by Django 5.2.5 on 2025-09-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0003_alter_userpredictionhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predhistory',
            name='predicted_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
